version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/venv
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - sikumai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - EXPO_PUBLIC_API_URL=http://localhost:5000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/web-build
    networks:
      - sikumai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - sikumai-network

volumes:
  redis_data:

networks:
  sikumai-network:
    driver: bridge 